In [1]:
import pandas as pd
import numpy as np

In [2]:
arr = [[55, 35, 24], [69, 19, 9], [11, 4, 1]]

In [3]:
arr = np.array(arr)
arr

array([[55, 35, 24],
       [69, 19,  9],
       [11,  4,  1]])

In [4]:
arr.sort()

In [5]:
arr

array([[24, 35, 55],
       [ 9, 19, 69],
       [ 1,  4, 11]])

In [6]:
arr.sort(axis = 0)

In [7]:
arr

array([[ 1,  4, 11],
       [ 9, 19, 55],
       [24, 35, 69]])

In [8]:
arr.T

array([[ 1,  9, 24],
       [ 4, 19, 35],
       [11, 55, 69]])

In [9]:
np.flip(arr, axis = 1)

array([[11,  4,  1],
       [55, 19,  9],
       [69, 35, 24]])

In [10]:
np.flip(arr)

array([[69, 35, 24],
       [55, 19,  9],
       [11,  4,  1]])

In [11]:
arr = [[55, 35, 24], [69, 19, 9], [11, 4, 1]]
arr.sort()
arr = np.array(arr)
arr

array([[11,  4,  1],
       [55, 35, 24],
       [69, 19,  9]])

In [12]:
np.flip(arr)

array([[ 9, 19, 69],
       [24, 35, 55],
       [ 1,  4, 11]])

In [13]:
a = np.array([1, 2, 3, 4, 5], dtype = 'int64')

In [14]:
a.itemsize

8

In [15]:
b = np.array([2, 3, 4])
b.itemsize

4

In [16]:
b.data

In [17]:
c = np.sin(np.linspace(0, np.pi, 11))
c

array([0.00000000e+00, 3.09016994e-01, 5.87785252e-01, 8.09016994e-01,
       9.51056516e-01, 1.00000000e+00, 9.51056516e-01, 8.09016994e-01,
       5.87785252e-01, 3.09016994e-01, 1.22464680e-16])

In [18]:
d = np.array([[1, 2, 3, 4],[5, 6, 3, 4],[7, 8, 3, 4],[9, 9, 3, 4]])
d

array([[1, 2, 3, 4],
       [5, 6, 3, 4],
       [7, 8, 3, 4],
       [9, 9, 3, 4]])

In [19]:
d[1:][0:2]

array([[5, 6, 3, 4],
       [7, 8, 3, 4]])